# Generated by Django 6.0.2 on 2026-02-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du compte')),
                ('account_type', models.CharField(choices=[('checking', 'Compte Courant'), ('savings', 'Compte Épargne'), ('credit_card', 'Carte de Crédit'), ('cash', 'Espèces'), ('investment', 'Investissement'), ('loan', 'Prêt'), ('other', 'Autre')], default='checking', max_length=20, verbose_name='Type de compte')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Solde')),
                ('currency', models.CharField(choices=[('CHF', 'Franc Suisse'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre Sterling')], default='CHF', max_length=3, verbose_name='Devise')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'db_table': 'account',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='account_user_id_66b9fa_idx'), models.Index(fields=['account_type'], name='account_account_1922e5_idx')],
            },
        ),
    ]
