# Generated by Django 6.0.2 on 2026-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Champ legacy - utiliser get_current_balance() ou get_projected_balance() pour obtenir le solde', max_digits=15, verbose_name='Solde'),
        ),
    ]
