# Generated by Django 6.0.2 on 2026-02-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0.0, help_text='Revenu mensuel total disponible pour les budgets', max_digits=15, verbose_name='Revenu mensuel')),
                ('currency', models.CharField(choices=[('CHF', 'Franc Suisse'), ('EUR', 'Euro'), ('USD', 'Dollar US'), ('GBP', 'Livre Sterling')], default='CHF', max_length=3, verbose_name='Devise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
                'db_table': 'user_profile',
            },
        ),
    ]
