# Generated by Django 6.0.2 on 2026-02-11 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this token (e.g., "iPhone Shortcut")', max_length=100, verbose_name='Token Name')),
                ('token', models.CharField(help_text='The actual API token (auto-generated)', max_length=64, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Last Used')),
                ('is_active', models.BooleanField(default=True, help_text='Disable token without deleting it', verbose_name='Active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'api_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='api_token_token_5cc0f7_idx'), models.Index(fields=['user', 'is_active'], name='api_token_user_id_a21fea_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unknown_category', 'Catégorie inconnue')], max_length=30, verbose_name="Type d'alerte")),
                ('payload', models.JSONField(default=dict, verbose_name='Données')),
                ('seen', models.BooleanField(default=False, verbose_name='Vue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Alerte en attente',
                'verbose_name_plural': 'Alertes en attente',
                'db_table': 'pending_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'seen'], name='pending_ale_user_id_9e61dd_idx')],
            },
        ),
    ]
