# Generated by Django 5.0.1 on 2026-02-13 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_apitoken_pendingalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary_day',
            field=models.IntegerField(blank=True, help_text='Jour du mois où le salaire est versé (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Jour du salaire'),
        ),
    ]
