# Generated by Django 6.0.2 on 2026-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_savings_goal',
            field=models.BooleanField(default=False, help_text='Si coché, ce budget suit les transferts vers comptes épargne au lieu des dépenses', verbose_name="Objectif d'épargne"),
        ),
    ]
