# Generated by Django 6.0.2 on 2026-02-11 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name="Nom de l'objectif")),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant cible')),
                ('product_url', models.URLField(blank=True, null=True, verbose_name='URL du produit')),
                ('product_image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image")),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Date cible')),
                ('saving_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Montant d'épargne par période")),
                ('saving_frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name="Fréquence d'épargne")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('reached', 'Atteint'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Objectif d'épargne",
                'verbose_name_plural': "Objectifs d'épargne",
                'db_table': 'savings_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='budgets.savingsgoal', verbose_name="Objectif d'épargne lié"),
        ),
    ]
