# Generated by Django 5.0.1 on 2026-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_savingsgoal_budget_savings_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_mandatory_savings',
            field=models.BooleanField(default=False, help_text="Si coché, ce budget compte comme une dépense obligatoire mensuelle (ex: épargne de précaution, fond d'urgence)", verbose_name='Épargne obligatoire'),
        ),
    ]
