# Generated by Django 6.0.2 on 2026-02-03 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense'), ('transfer', 'Transfert')], max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Récurrent')),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20, null=True, verbose_name='Fréquence')),
                ('recurrence_interval', models.IntegerField(blank=True, default=1, null=True, verbose_name='Intervalle')),
                ('recurrence_end_date', models.DateField(blank=True, null=True, verbose_name='Fin de récurrence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='Compte')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category', verbose_name='Catégorie')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='accounts.account', verbose_name='Compte destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_202735_idx'), models.Index(fields=['account', 'date'], name='transaction_account_7a5a4c_idx'), models.Index(fields=['category', 'date'], name='transaction_categor_86593e_idx'), models.Index(fields=['type', 'date'], name='transaction_type_2cae2c_idx')],
            },
        ),
    ]
