# Generated by Django 6.0.2 on 2026-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Revenu'), ('expense', 'Dépense'), ('transfer', 'Transfert'), ('adjustment', 'Ajustement de solde')], max_length=10, verbose_name='Type'),
        ),
    ]
