# Generated by Django 6.0.2 on 2026-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('ios', 'iOS'), ('ios_uncategorized', 'iOS (non catégorisé)')], default='web', max_length=20, verbose_name='Source'),
        ),
    ]
